version: "3"

services:
    parser:
      build: .
      working_dir: /survey-processor
      command: python app.py ${SURVEY_FILE} ${RESPONSE_FILE}
      volumes:
        - ./:/survey-processor
      tty: true
      stdin_open: true